import { format } from 'date-fns';
import type { CourseExportData } from '../types';

export function generateCourseWord(d: CourseExportData): Blob {
  const rows = d.courses.map((c, i) =>
    '<tr style="background:' + (i % 2 === 0 ? '#F9FAFB' : 'white') + ';">'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">' + (i + 1) + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + c.name + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + c.date + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (c.provider || '—') + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (c.duration || '—') + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (c.hasCertificate ? 'Yes' : 'No') + '</td>'
    + '</tr>'
  ).join('');

  const html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">'
    + '<head><meta charset="utf-8"><title>Courses Logbook</title>'
    + '<style>body{font-family:Arial,sans-serif;margin:40px;color:#1F2937;} @page{margin:2cm;}</style></head>'
    + '<body>'
    + '<div style="border-bottom:1px solid #E5E7EB;padding-bottom:16px;margin-bottom:24px;">'
    + '<div style="display:flex;justify-content:space-between;align-items:flex-start;">'
    + '<div>'
    + '<div style="font-size:24pt;font-weight:bold;color:#1F2937;margin-bottom:4px;">Courses Logbook</div>'
    + '<div style="font-size:12pt;color:#6B7280;">' + d.doctorName + '</div>'
    + (d.period ? '<div style="font-size:11pt;color:#9CA3AF;">' + d.period.from + ' — ' + d.period.to + '</div>' : '')
    + '</div>'
    + '<div style="text-align:right;font-size:11pt;color:#9CA3AF;">' + format(new Date(), 'dd MMM yyyy') + '<br>Medora</div>'
    + '</div></div>'
    + '<div style="font-size:18pt;font-weight:bold;color:#1F2937;padding-bottom:6px;border-bottom:1px solid #E5E7EB;margin-bottom:12px;">Summary</div>'
    + '<table style="width:100%;border-collapse:collapse;margin-bottom:24px;">'
    + '<tr style="background:#F3F4F6;"><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;width:50%;">Total Courses</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.total + '</td></tr>'
    + '<tr><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">With Certificate</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.withCertificate + '</td></tr>'
    + '</table>'
    + '<div style="font-size:18pt;font-weight:bold;color:#1F2937;padding-bottom:6px;border-bottom:1px solid #E5E7EB;margin-bottom:12px;">Courses Log</div>'
    + '<table style="width:100%;border-collapse:collapse;margin-bottom:24px;">'
    + '<tr style="background:#F3F4F6;">'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">#</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">Course Name</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">Date</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">Provider</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">Duration</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;">Certificate</th>'
    + '</tr>'
    + rows + '</table>'
    + '<div style="border-top:1px solid #E5E7EB;padding-top:12px;text-align:center;font-size:10pt;color:#9CA3AF;">'
    + 'Generated by Medora \u00b7 Confidential \u2014 Medical use only'
    + '</div></body></html>';

  return new Blob([html], { type: 'application/msword' });
}
