import jsPDF from 'jspdf';
// @ts-ignore
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { CourseExportData } from '../types';

export async function generateCoursePlainPDF(d: CourseExportData): Promise<Blob> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = 595, PL = 50, PR = 50;
  const DARK    = [31, 41, 55]    as [number,number,number];
  const MUTED   = [107, 114, 128] as [number,number,number];
  const FOOTER_C= [156, 163, 175] as [number,number,number];
  const BORDER  = [229, 231, 235] as [number,number,number];
  const ZEBRA   = [243, 244, 246] as [number,number,number];

  // ── HEADER ──────────────────────────────────────────────────────────────
  doc.setFontSize(24); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Courses Logbook', PL, 40);

  doc.setFontSize(12); doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(d.doctorName, PL, 58);
  if (d.institution) doc.text(d.institution, PL, 72);
  if (d.period) doc.text(`${d.period.from} — ${d.period.to}`, PL, d.institution ? 86 : 72);

  doc.setFontSize(11); doc.setTextColor(...MUTED);
  doc.text(format(new Date(), 'dd MMM yyyy'), W - PR, 40, { align: 'right' });

  const headerBottom = d.period ? (d.institution ? 96 : 82) : (d.institution ? 82 : 68);
  doc.setDrawColor(...BORDER); doc.setLineWidth(1);
  doc.line(PL, headerBottom, W - PR, headerBottom);

  // ── SUMMARY ──────────────────────────────────────────────────────────────
  let sy = headerBottom + 14;
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Summary', PL, sy);
  doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
  doc.line(PL, sy + 6, W - PR, sy + 6);
  sy += 20;

  [
    ['Total Courses',    String(d.stats.total)],
    ['With Certificate', String(d.stats.withCertificate)],
  ].forEach((r, i) => {
    if (i % 2 === 0) { doc.setFillColor(...ZEBRA); doc.rect(PL, sy, W - PL - PR, 22, 'F'); }
    doc.setDrawColor(...BORDER); doc.setLineWidth(0.3);
    doc.rect(PL, sy, W - PL - PR, 22);
    doc.setFontSize(11); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED); doc.text(r[0], PL + 8, sy + 15);
    doc.setFont('helvetica', 'bold'); doc.setTextColor(...DARK);
    doc.text(r[1], PL + 200, sy + 15);
    sy += 22;
  });

  // ── TABLE ────────────────────────────────────────────────────────────────
  const tableY = sy + 20;
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Courses Log', PL, tableY);
  doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
  doc.line(PL, tableY + 6, W - PR, tableY + 6);

  autoTable(doc, {
    startY: tableY + 16,
    head: [['#', 'Course Name', 'Date', 'Provider', 'Duration', 'Certificate']],
    body: d.courses.map((c, i) => [
      i + 1, c.name, c.date,
      c.provider || '—', c.duration || '—',
      c.hasCertificate ? 'Yes' : 'No',
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: ZEBRA, textColor: DARK, fontStyle: 'bold', fontSize: 9, lineColor: BORDER, lineWidth: 0.3 },
    alternateRowStyles: { fillColor: [249, 250, 251] as [number,number,number] },
    tableLineColor: BORDER, tableLineWidth: 0.3,
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 150 },
      2: { cellWidth: 65 },
      3: { cellWidth: 100 },
      4: { cellWidth: 60 },
      5: { cellWidth: 56 },
    },
    margin: { left: PL, right: PR },
  });

  // ── FOOTER ───────────────────────────────────────────────────────────────
  const pages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
    doc.line(PL, 820, W - PR, 820);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...FOOTER_C);
    doc.text('Generated by Medora', PL, 833);
    doc.text('Confidential — Medical use only', W - PR, 833, { align: 'right' });
    doc.text(`Page ${i} of ${pages}`, W / 2, 833, { align: 'center' });
  }

  return doc.output('blob');
}
