import jsPDF from 'jspdf';
// @ts-ignore
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { ProcedureExportData } from '../types';

export async function generateProcedurePlainPDF(d: ProcedureExportData): Promise<Blob> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = 595, PL = 50, PR = 50, CW = W - PL - PR;
  const DARK    = [31, 41, 55]    as [number,number,number];
  const MUTED   = [107, 114, 128] as [number,number,number];
  const FOOTER_C= [156, 163, 175] as [number,number,number];
  const BORDER  = [229, 231, 235] as [number,number,number];
  const ZEBRA   = [243, 244, 246] as [number,number,number];

  // ── HEADER ──────────────────────────────────────────────────────────────
  doc.setFontSize(24); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Procedures Logbook', PL, 40);

  doc.setFontSize(12); doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  const specLine = [d.doctorName, d.specialty].filter(Boolean).join(' · ');
  doc.text(specLine, PL, 58);
  if (d.institution) { doc.text(d.institution, PL, 72); }

  doc.setFontSize(11); doc.setTextColor(...MUTED);
  doc.text(format(new Date(), 'dd MMM yyyy'), W - PR, 40, { align: 'right' });

  doc.setDrawColor(...BORDER); doc.setLineWidth(1);
  doc.line(PL, d.hospital ? 82 : 68, W - PR, d.hospital ? 82 : 68);
  const y0 = d.hospital ? 98 : 84;

  // ── SUMMARY TABLE ────────────────────────────────────────────────────────
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Summary', PL, y0 + 14);
  doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
  doc.line(PL, y0 + 20, W - PR, y0 + 20);

  const summaryRows = [
    ['Total Procedures', String(d.stats.total)],
    ['Performed',        String(d.stats.performed)],
    ['Assisted',         String(d.stats.assisted)],
    ['Observed',         String(d.stats.observed)],
  ];
  let sy = y0 + 28;
  summaryRows.forEach((r, i) => {
    if (i % 2 === 0) { doc.setFillColor(...ZEBRA); doc.rect(PL, sy, CW, 22, 'F'); }
    doc.setDrawColor(...BORDER); doc.setLineWidth(0.3);
    doc.rect(PL, sy, CW, 22);
    doc.setFontSize(11); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED); doc.text(r[0], PL + 8, sy + 15);
    doc.setFont('helvetica', 'bold'); doc.setTextColor(...DARK);
    doc.text(r[1], PL + 200, sy + 15);
    sy += 22;
  });

  // ── PROCEDURES TABLE ─────────────────────────────────────────────────────
  const tableY = sy + 24;
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Procedures Log', PL, tableY);
  doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
  doc.line(PL, tableY + 6, W - PR, tableY + 6);

  autoTable(doc, {
    startY: tableY + 16,
    head: [['#', 'Procedure', 'Date', 'Role', 'Patient', 'Supervisor', 'Indication']],
    body: d.procedures.map((p, i) => [
      i + 1,
      p.name,
      p.date,
      p.participation.charAt(0).toUpperCase() + p.participation.slice(1),
      p.patientName || '—',
      p.supervisor || '—',
      p.indication || '—',
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: ZEBRA, textColor: DARK, fontStyle: 'bold', fontSize: 9, lineColor: BORDER, lineWidth: 0.3 },
    alternateRowStyles: { fillColor: [249, 250, 251] as [number,number,number] },
    tableLineColor: BORDER, tableLineWidth: 0.3,
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 85 },
      2: { cellWidth: 62 },
      3: { cellWidth: 62 },
      4: { cellWidth: 72 },
      5: { cellWidth: 72 },
      6: { cellWidth: 68 },
    },
    margin: { left: PL, right: PR },
  });

  // ── FOOTER ───────────────────────────────────────────────────────────────
  const pages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
    doc.line(PL, 820, W - PR, 820);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...FOOTER_C);
    doc.text('Generated by Medora', PL, 833);
    doc.text('Confidential — Medical use only', W - PR, 833, { align: 'right' });
    doc.text(`Page ${i} of ${pages}`, W / 2, 833, { align: 'center' });
  }

  return doc.output('blob');
}
