import { format } from 'date-fns';
import type { ProcedureExportData } from '../types';

export function generateProcedureWord(d: ProcedureExportData): Blob {
  const rows = d.procedures.map((p, i) =>
    '<tr style="background:' + (i % 2 === 0 ? '#F9FAFB' : 'white') + ';">'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">' + (i + 1) + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + p.name + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + p.date + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;">' + (p.participation.charAt(0).toUpperCase() + p.participation.slice(1)) + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (p.patientName || '—') + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (p.supervisor || '—') + '</td>'
    + '<td style="padding:8px;border:1px solid #E5E7EB;color:#374151;font-size:11pt;">' + (p.indication || '—') + '</td>'
    + '</tr>'
  ).join('');

  const html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">'
    + '<head><meta charset="utf-8"><title>Procedures Logbook</title>'
    + '<style>body{font-family:Arial,sans-serif;margin:40px;color:#1F2937;} @page{margin:2cm;}</style></head>'
    + '<body>'

    // Header
    + '<div style="border-bottom:1px solid #E5E7EB;padding-bottom:16px;margin-bottom:24px;">'
    + '<div style="display:flex;justify-content:space-between;align-items:flex-start;">'
    + '<div>'
    + '<div style="font-size:24pt;font-weight:bold;color:#1F2937;margin-bottom:4px;">Procedures Logbook</div>'
    + '<div style="font-size:12pt;color:#6B7280;">' + d.doctorName + (d.specialty ? ' \u00b7 ' + d.specialty : '') + '</div>'
    + (d.hospital ? '<div style="font-size:12pt;color:#6B7280;">' + d.hospital + '</div>' : '')
    + '</div>'
    + '<div style="text-align:right;font-size:11pt;color:#9CA3AF;">' + format(new Date(), 'dd MMM yyyy') + '<br>Medora</div>'
    + '</div></div>'

    // Summary
    + '<div style="font-size:18pt;font-weight:bold;color:#1F2937;padding-bottom:6px;border-bottom:1px solid #E5E7EB;margin-bottom:12px;">Summary</div>'
    + '<table style="width:100%;border-collapse:collapse;margin-bottom:24px;">'
    + '<tr style="background:#F3F4F6;"><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;width:50%;">Total Procedures</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.total + '</td></tr>'
    + '<tr><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">Performed</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.performed + '</td></tr>'
    + '<tr style="background:#F3F4F6;"><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">Assisted</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.assisted + '</td></tr>'
    + '<tr><td style="padding:8px;border:1px solid #E5E7EB;color:#6B7280;font-size:11pt;">Observed</td><td style="padding:8px;border:1px solid #E5E7EB;color:#1F2937;font-size:11pt;font-weight:bold;">' + d.stats.observed + '</td></tr>'
    + '</table>'

    // Procedures table
    + '<div style="font-size:18pt;font-weight:bold;color:#1F2937;padding-bottom:6px;border-bottom:1px solid #E5E7EB;margin-bottom:12px;">Procedures Log</div>'
    + '<table style="width:100%;border-collapse:collapse;margin-bottom:24px;">'
    + '<tr style="background:#F3F4F6;">'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">#</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Procedure</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Date</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Role</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Patient</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Supervisor</th>'
    + '<th style="padding:8px;border:1px solid #E5E7EB;text-align:left;font-size:11pt;color:#1F2937;">Indication</th>'
    + '</tr>'
    + rows
    + '</table>'

    // Footer
    + '<div style="border-top:1px solid #E5E7EB;padding-top:12px;text-align:center;font-size:10pt;color:#9CA3AF;">'
    + 'Generated by Medora \u00b7 Confidential \u2014 Medical use only'
    + '</div>'
    + '</body></html>';

  return new Blob([html], { type: 'application/msword' });
}
