import jsPDF from 'jspdf';
// @ts-ignore
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { LectureExportData } from '../types';

export async function generateLecturePlainPDF(d: LectureExportData): Promise<Blob> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = 595, PL = 50, PR = 50;
  const DARK    = [31, 41, 55]    as [number,number,number];
  const MUTED   = [107, 114, 128] as [number,number,number];
  const FOOTER_C= [156, 163, 175] as [number,number,number];
  const BORDER  = [229, 231, 235] as [number,number,number];
  const ZEBRA   = [243, 244, 246] as [number,number,number];

  // ── HEADER ──────────────────────────────────────────────────────────────
  doc.setFontSize(24); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Lectures Logbook', PL, 40);

  doc.setFontSize(12); doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(d.doctorName, PL, 58);
  if (d.institution) doc.text(d.institution, PL, 72);
  if (d.period) doc.text(`${d.period.from} — ${d.period.to}`, PL, d.institution ? 86 : 72);

  doc.setFontSize(11); doc.setTextColor(...MUTED);
  doc.text(format(new Date(), 'dd MMM yyyy'), W - PR, 40, { align: 'right' });

  const headerBottom = d.period ? (d.institution ? 96 : 82) : (d.institution ? 82 : 68);
  doc.setDrawColor(...BORDER); doc.setLineWidth(1);
  doc.line(PL, headerBottom, W - PR, headerBottom);

  const tableY = headerBottom + 16;
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Lectures Log', PL, tableY);
  doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
  doc.line(PL, tableY + 6, W - PR, tableY + 6);

  // ── TABLE ────────────────────────────────────────────────────────────────
  autoTable(doc, {
    startY: tableY + 16,
    head: [['#', 'Topic', 'Date', 'Speaker', 'Duration', 'Location']],
    body: d.lectures.map((l, i) => [
      i + 1, l.topic, l.date,
      l.speaker || '—', l.duration || '—', l.location || '—',
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: ZEBRA, textColor: DARK, fontStyle: 'bold', fontSize: 9, lineColor: BORDER, lineWidth: 0.3 },
    alternateRowStyles: { fillColor: [249, 250, 251] as [number,number,number] },
    tableLineColor: BORDER, tableLineWidth: 0.3,
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 145 },
      2: { cellWidth: 65 },
      3: { cellWidth: 90 },
      4: { cellWidth: 60 },
      5: { cellWidth: 71 },
    },
    margin: { left: PL, right: PR },
  });

  // ── FOOTER ───────────────────────────────────────────────────────────────
  const pages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BORDER); doc.setLineWidth(0.5);
    doc.line(PL, 820, W - PR, 820);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...FOOTER_C);
    doc.text('Generated by Medora', PL, 833);
    doc.text('Confidential — Medical use only', W - PR, 833, { align: 'right' });
    doc.text(`Page ${i} of ${pages}`, W / 2, 833, { align: 'center' });
  }

  return doc.output('blob');
}
