import jsPDF from 'jspdf';
// @ts-ignore
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { LectureExportData } from '../types';

export async function generateLectureClinicalPDF(d: LectureExportData): Promise<Blob> {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const W = 595, PL = 40, PR = 40, CW = W - PL - PR;
  const BLUE  = [24, 73, 169]   as [number,number,number];
  const TEAL  = [8, 145, 178]   as [number,number,number];
  const MUTED = [148, 163, 184] as [number,number,number];
  const DARK  = [26, 35, 50]    as [number,number,number];
  const BG    = [248, 250, 252] as [number,number,number];

  // ── HEADER ──────────────────────────────────────────────────────────────
  doc.setFillColor(...BLUE);
  doc.rect(0, 0, W, 110, 'F');

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(PL, 18, 34, 34, 4, 4, 'F');
  doc.setFontSize(20); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLUE);
  doc.text('M', PL + 17, 40, { align: 'center' });

  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('Medora', PL + 44, 32);
  doc.setFontSize(8); doc.setFont('helvetica', 'normal');
  doc.setTextColor(147, 197, 253);
  doc.text('MEDICAL LOGBOOK', PL + 44, 44);

  doc.setFontSize(10); doc.setTextColor(147, 197, 253);
  doc.text('Lectures Logbook', W - PR, 28, { align: 'right' });
  doc.text(format(new Date(), 'dd MMM yyyy'), W - PR, 40, { align: 'right' });
  if (d.period) doc.text(`${d.period.from} — ${d.period.to}`, W - PR, 52, { align: 'right' });

  // Doctor bar
  doc.setFillColor(50, 100, 190);
  doc.roundedRect(PL, 56, CW, 40, 6, 6, 'F');
  doc.setFontSize(14); doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(d.doctorName, PL + 14, 72);
  if (d.institution) {
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.setTextColor(147, 197, 253);
    doc.text(d.institution, PL + 14, 86);
  }
  doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  doc.setTextColor(147, 197, 253);
  doc.text('Lectures Attended', W - PR - 14, 68, { align: 'right' });
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(String(d.stats.total), W - PR - 14, 86, { align: 'right' });

  let y = 122;

  // ── SECTION HEADER ────────────────────────────────────────────────────────
  doc.setFillColor(...TEAL);
  doc.rect(PL, y, 3, 16, 'F');
  doc.setFontSize(11); doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEAL);
  doc.text('LECTURES LOG', PL + 10, y + 12);
  y += 22;

  // ── TABLE ────────────────────────────────────────────────────────────────
  autoTable(doc, {
    startY: y,
    head: [['#', 'Topic', 'Date', 'Speaker', 'Duration', 'Location']],
    body: d.lectures.map((l, i) => [
      i + 1,
      l.topic,
      l.date,
      l.speaker  || '—',
      l.duration || '—',
      l.location || '—',
    ]),
    styles: { fontSize: 8, cellPadding: 5 },
    headStyles: { fillColor: TEAL, fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: BG },
    columnStyles: {
      0: { cellWidth: 24 },
      1: { cellWidth: 140 },
      2: { cellWidth: 65 },
      3: { cellWidth: 90 },
      4: { cellWidth: 60 },
      5: { cellWidth: 76 },
    },
    margin: { left: PL, right: PR },
  });

  // ── FOOTER ───────────────────────────────────────────────────────────────
  const pages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240); doc.setLineWidth(0.5);
    doc.line(PL, 820, W - PR, 820);
    doc.setFontSize(9); doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text('Generated by Medora', PL, 832);
    doc.text('Confidential — Medical use only', W - PR, 832, { align: 'right' });
    doc.text(`Page ${i} of ${pages}`, W / 2, 832, { align: 'center' });
  }

  return doc.output('blob');
}
